apiVersion: v1
kind: Service
metadata:
  name: platformservice-clusterip
spec:
  selector:
    app: platformservice
  ports:
    - name: ps-http
      port: 8080
      targetPort: 8080
    - name: ps-grpc
      port: 666
      targetPort: 666
