apiVersion: v1
kind: Service
metadata:
  name: platformservice-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: platformservice-mssql
  ports:
    - port: 1433
      targetPort: 1433
