apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rmq-mgmt-port
      port: 15672
      targetPort: 15672
    - name: rmq-msg-port
      port: 5672
      targetPort: 5672
